dist: trusty
language: python
python:
  - "3.6"
cache: pip

before_install:
  - psql -c "create user username with encrypted password 'password';" -U postgres
  - psql -c "create database yourdatabase with owner username;" -U postgres
  - psql -c "alter user username createdb;" -U postgres
  - pip install coverage
  - pip install sphinx

sudo: false
addons:
  apt:
    packages:
    - samtools
    - pandoc

script:
  - python setup.py install
  - django-admin startproject WEBPROJECT
  - export PYTHONPATH=`pwd`; coverage run WEBPROJECT/manage.py test machado --settings machado.tests.settings

after_success:
  - pip install codecov
  - codecov

notifications:
  email: false
