image: python:3.5.1
pipelines:
  defautl:
    - step:
      script:
        - python setup.py install
        - django-admin startproject WEBPROJECT
        - python WEBPROJECT/manage.py test chado --settings chado/tests/settings.py
      services:
        - postgres

definitions:
  service:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: 'yourdatabase'
        POSTGRES_USER: 'username'
        POSTGRES_PASSWORD: 'password'
