image: ubuntu:17.10
pipelines:
  default:
    - step:
        script:
          - apt-get update && apt-get install -y python3 python3-dev samtools libbambamc-dev libbambamc0 pandoc
          - python3.6 setup.py install
          - django-admin startproject WEBPROJECT
          - python3.6 WEBPROJECT/manage.py test chado --settings chado.tests.settings
        services:
          - postgres
definitions: 
  services: 
    postgres: 
      image: postgres
      environment:
        POSTGRES_DB: 'yourdatabase'
        POSTGRES_USER: 'username'
        POSTGRES_PASSWORD: 'password'
