image: ubuntu
pipelines:
  default:
    - step:
        script:
          - apt-get install python3.6 python3.6-dev samtools libbambamc-dev libbambamc0 pandoc 
          - python3.6 setup.py install
          - django-admin startproject WEBPROJECT
          - python3.6 WEBPROJECT/manage.py test chado --settings chado/tests/settings.py
        services:
          - postgres
definitions: 
  services: 
    postgres: 
      image: postgres
      environment:
        POSTGRES_DB: 'yourdatabase'
        POSTGRES_USER: 'username'
        POSTGRES_PASSWORD: 'password'
